#pragma once
#ifndef __BOSSONE_ANIMATION_STATE__
#define __BOSSONE_ANIMATION_STATE__

enum BossOneAnimationState
{
	BOSSONE_IDLE_RIGHT,
	BOSSONE_IDLE_LEFT,
	BOSSONE_RUN_RIGHT,
	BOSSONE_RUN_LEFT,
	NUM_OF_BOSSANIMATION_STATES
};

#endif /* defined (__BOSSONE_ANIMATION_STATE__)*/