#pragma once
#ifndef __BOSSONE_ANIMATION_STATE__
#define __BOSSONE_ANIMATION_STATE__

enum BossOneAnimationState
{
	BOSSONE_WALK_DOWN,
	BOSSONE_WALK_RIGHT,
	BOSSONE_WALK_LEFT,
	BOSSONE_WALK_UP,
	NUM_OF_BOSSANIMATION_STATES
};

#endif /* defined (__BOSSONE_ANIMATION_STATE__)*/