#pragma once
#ifndef __PLAYER_ANIMATION_STATE__
#define __PLAYER_ANIMATION_STATE__

enum PlayerAnimationState
{
	PLAYER_RUN_UP,
	PLAYER_RUN_DOWN,
	PLAYER_RUN_LEFT,
	PLAYER_RUN_RIGHT,
	ABILITY_UP,
	ABILITY_RIGHT,
	ABILITY_DOWN,
	ABILITY_LEFT
	
};

#endif /* defined (__PLAYER_ANIMATION_STATE__)*/